### PR TITLE
Add Fabric Support (+ Fix Security Issues and Code Cleanup)

### PR DESCRIPTION
**Pull request by ZandercraftGames**
This pull request adds fabric support and resolves a few issues with the old PR from Kio. This should be completely compatible to merge into the master branch as it has all of the latest changes as well.

### CODE REVIEW

**Comment by ZandercraftGames** [comment]
These changes have also been reflected in #28 meaning that this can be merged alongside that PR as well to properly add support on both branches. This should also keep with fixing the dev branch having the old changelog and detecting a non-existent update (trying to get you to downgrade).

**Comment by ZandercraftGames** [comment]
Do not merge this yet. I am working on some changes and need to verify that everything works fine first. It needs testing with the latest changes.

**Comment by Kio-td** [comment]
Folks, just in case you haven't seen it yet, Solder.cf has gone stale.
Just to put my foot down here and now, I will personally not be maintaining Solder.cf any longer, as I have other projects that I will be maintaining. I believe the author has said it aswell, that he will also be pursuing other projects, so please consider my message before you clone this repo. :)

For those who wish to continue working on it, I wish you the best. Looking at this code from a fresh set of eyes, I really do suggest that people use either Zandercraft's Fork of Solder.cf (which has a few security upgrades - making password theft more difficult, and removing some of the invasive codes that were left by the previous creators) or they completely rework a new Soldering system.

Not to say that TheGameSpider's project was wonderful - it has been. I loved working on this palace from behind the scenes. But this script hasn't aged too well, being a being peice of spaghetti really hurts the eyes. and is heck and a half to debug.

Another couple of things I'd like to give as a quick mention,
- The Fabric port I made is still just that, a little fabric port to s.cf, hastily thrown together and bound to s.cf with about 10 Liters of FlexTape:tm:. If Copilot was available when I made that feature, it'd have deleted all my code and told me to start over. Please keep this in mind, if Fabric breaks the little patch-in job I made, I ain't going to fix it.

- As much as I wished to add in Curseforge->Technic support, it seems like Overwolf/CurseForge are [getting rid of 3rd party support](https://www.reddit.com/r/feedthebeast/comments/uswnhe/psa_curseforge_has_started_enforcing_restrictions/) with their undocumented APIs. Using these APIs eitherway prevent creators from getting money they deserve, and I'm not about to start building on-the-fly scrapers for PHP so people can have mods while simutaneously hitting Curseforge's monetization system (not to mention the potential for abuse that comes with it, and getting the people who use said system banned).


\o Thanks, and bon voyage, my friends!
Enjoy playing minecraft. You deserve it.

**Comment by ZandercraftGames** [comment]
This is technically in a mergeable state, however I'm still working on a lot of code cleanup behind the scenes. Whether that comes in this update or the next is up to you @TheGameSpider. Once this one is merged, I will bring the dev branch up to date and you can then merge #28 (this one must be merged first.).

This has some extremely important updates regarding security that really should be pushed out there as soon as possible.

**Comment by ZandercraftGames** [comment]
There we are :)
This should be ready to be merged. I've also got #28 ready for merge after this one.

**Pull request merged**
